### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by blindpirate** [nathansgreen/hg4j#2]
Recently I want to integrate hg4j into my production project, is it safe to do that?

PS. where are the documentations and samples?

Thank you.

**Comment by nathansgreen** [comment]
As far as I know, the code has not changed in about 2½ years. I just cloned it from hg4j.com because I needed to do some experiments. I don't know about any documentation, but the test cases are what I used as sample code. Note that the project appears to be GPLv2 (see [COPYING](../blob/master/COPYING)).
